version: '2'

services:
  facedetect:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    restart: unless-stopped
    volumes:
      - ./enrrolados:/docker/enrrolados 
      - ./temp:/docker/temp 
