version: '1'

services:
  facedetect:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    restart: unless-stopped
    volumes:
      - ./enrrolados:/docker/enrrolados 
      - ./temp:/docker/temp 
