name: Test

on: push
jobs:
  docker-test:
    timeout-minutes: 25
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "RicardoValladares" --password-stdin
        docker image build -t ricardovalladares/facedetect:latest .
        docker push ricardovalladares/facedetect:latest
