name: Test

on: push
jobs:
  docker-test:
    timeout-minutes: 25
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERPW }}
    - name: Build FaceDetect Docker image
      run: |
       docker build . --tag ghcr.io/ricardovalladares/facedetect:latest
       docker run ghcr.io/ricardovalladares/facedetect:latest
       docker push ghcr.io/ricardovalladares/facedetect:latest

