name: Test

on: push
jobs:
  docker-test:
    timeout-minutes: 25
    runs-on: ubuntu-22.04

    steps:
      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: RicardoValladares
          password: 17092022Veronica

      - name: Publish to Github Container registry
        run: docker push ghcr.io/ricardovalladares/facedetect:latest

